// personal-blog-react/src/pages/CategoriesPage.tsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import Layout from '../components/Layout';
import { Category, BlogPost } from '../types';
import { getCategories, addCategory, deleteCategory } from '../data/categoryManager';
import './CategoriesPage.css';

// 从localStorage获取所有文章
const getBlogPostsFromLocalStorage = (): BlogPost[] => {
  try {
    const posts = JSON.parse(localStorage.getItem('blogPosts') || '[]');
    return posts as BlogPost[];
  } catch (error) {
    console.error('Failed to load blog posts from localStorage:', error);
    return [];
  }
};

const CategoriesPage: React.FC = () => {
  const [categories, setCategories] = useState<Category[]>([]);
  const [newCategoryName, setNewCategoryName] = useState('');
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [message, setMessage] = useState('');

  // 加载分类数据
  const loadCategories = () => {
    const cats = getCategories();
    setCategories(cats);
  };

  useEffect(() => {
    // 从localStorage加载文章
    const blogPosts = getBlogPostsFromLocalStorage();
    setPosts(blogPosts);
    // 加载分类数据
    loadCategories();
  }, []);

  // 添加新分类
  const handleAddCategory = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newCategoryName.trim()) return;

    const success = addCategory(newCategoryName.trim());
    if (success) {
      setMessage('分类添加成功！');
      setNewCategoryName('');
      loadCategories(); // 重新加载分类
    } else {
      setMessage('分类已存在！');
    }

    // 3秒后清除消息
    setTimeout(() => setMessage(''), 3000);
  };

  // 删除分类
  const handleDeleteCategory = (id: string) => {
    const success = deleteCategory(id);
    if (success) {
      setMessage('分类删除成功！');
      loadCategories(); // 重新加载分类
    } else {
      setMessage('删除失败，请重试！');
    }

    // 3秒后清除消息
    setTimeout(() => setMessage(''), 3000);
  };

  // 根据分类名称获取文章数量 - 现在从分类对象直接获取
  const getPostsCountByCategory = (categoryName: string) => {
    const category = categories.find(cat => cat.name === categoryName);
    return posts.filter(post => post.category === category?.name).length;
  };

  // 添加分类管理样式
  const style = `
    .add-category-form-container {
      margin-bottom: 30px;
      padding: 20px;
      background-color: #f9f9f9;
      border-radius: 8px;
    }

    .section-title {
      margin-top: 0;
      margin-bottom: 15px;
      color: #333;
    }

    .add-category-form {
      display: flex;
      gap: 10px;
    }

    .category-input {
      flex: 1;
      padding: 8px 12px;
      border: 1px solid #ddd;
      border-radius: 4px;
      font-size: 14px;
    }

    .add-category-button {
      padding: 8px 16px;
      background-color: #4a6fa5;
      color: white;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.2s;
    }

    .add-category-button:hover {
      background-color: #3a5a8c;
    }

    .category-message {
      margin-top: 10px;
      padding: 8px;
      border-radius: 4px;
      font-size: 14px;
      color: #333;
      background-color: #e8f4fd;
    }

    .category-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .delete-category-button {
      background: none;
      border: none;
      color: #ff4d4d;
      cursor: pointer;
      padding: 4px;
      opacity: 0.7;
      transition: opacity 0.2s;
    }

    .delete-category-button:hover {
      opacity: 1;
    }
  `;

  // 注入样式
  useEffect(() => {
    const styleElement = document.createElement('style');
    styleElement.textContent = style;
    document.head.appendChild(styleElement);

    return () => {
      document.head.removeChild(styleElement);
    };
  }, []);

  return (
    <Layout>
      <div className="categories-page">
        <h2 className="page-title">文章分类</h2>

        {/* 添加分类表单 */}
        <div className="add-category-form-container">
          <h3 className="section-title">添加新分类</h3>
          <form onSubmit={handleAddCategory} className="add-category-form">
            <input
              type="text"
              value={newCategoryName}
              onChange={(e) => setNewCategoryName(e.target.value)}
              placeholder="输入分类名称"
              className="category-input"
              required
            />
            <button type="submit" className="add-category-button">添加</button>
          </form>
          {message && <p className="category-message">{message}</p>}
        </div>

        {/* 分类列表 */}
        <div className="categories-list">
          {categories.map(category => (
            <div key={category.id} className="category-card">
              <div className="category-header">
                <Link to={`/category/${category.id}`} className="category-link">
                  <h3 className="category-name">{category.name}</h3>
                </Link>
                <button
                  onClick={() => handleDeleteCategory(category.id)}
                  className="delete-category-button"
                  aria-label={`删除分类 ${category.name}`}
                >
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="3 6 5 6 21 6"></polyline>
                    <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                  </svg>
                </button>
              </div>
              <div className="category-stats">
                <span className="category-count">{getPostsCountByCategory(category.name)} 篇文章</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </Layout>
  );
};

export default CategoriesPage;

// personal-blog-vue/src/views/CategoriesPage.vue
<template>
  <Layout sidebar="true">
    <div class="categories-page">
      <div class="page-header">
        <h1 class="page-title">文章分类</h1>
        <p class="page-description">浏览所有的文章分类，查看相关主题的内容</p>
      </div>
      
      <div class="categories-container">
        <div class="categories-list">
          <div 
            v-for="category in categories"
            :key="category.id"
            class="category-card"
          >
            <router-link :to="`/category/${category.id}`" class="category-link">
              <div class="category-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path>
                  <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path>
                </svg>
              </div>
              
              <div class="category-info">
                <h3 class="category-name">{{ category.name }}</h3>
                <p class="category-count">{{ category.count }} 篇文章</p>
                <p class="category-description">{{ getCategoryDescription(category.id) }}</p>
              </div>
            </router-link>
          </div>
        </div>
      </div>
    </div>
  </Layout>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { RouterLink } from 'vue-router';
import type { Category } from '../types';
import Layout from '../components/Layout.vue';

// 分类数据
const categories = ref<Category[]>([]);

// 获取分类描述
const getCategoryDescription = (categoryId: string) => {
  const descriptions: Record<string, string> = {
    '1': '前端开发相关的技术文章，包括JavaScript、Vue、React等框架的使用和技巧。',
    '2': '后端开发相关的技术文章，包括Node.js、Go、数据库等技术的使用和最佳实践。',
    '3': '数据库相关的技术文章，包括MySQL、MongoDB等数据库的使用和优化技巧。',
    '4': '开发工具和效率提升相关的文章，包括编辑器、终端、版本控制等工具的使用技巧。'
  };
  
  return descriptions[categoryId] || '该分类下的文章集合';
};

// 获取分类数据
const fetchCategories = async () => {
  try {
    // 模拟API请求延迟
    await new Promise(resolve => setTimeout(resolve, 300));
    
    // 从localStorage获取文章数据来计算每个分类的文章数量
    const storedArticles = localStorage.getItem('blogPosts');
    const articlesData = storedArticles ? JSON.parse(storedArticles) : [];
    
    // 初始化分类数据
    const initialCategories: Category[] = [
      { id: '1', name: '前端开发', count: 0 },
      { id: '2', name: '后端开发', count: 0 },
      { id: '3', name: '数据库', count: 0 },
      { id: '4', name: '工具技巧', count: 0 }
    ];
    
    // 计算每个分类的文章数量
    initialCategories.forEach(category => {
      category.count = articlesData.filter((article: any) => 
        article.category && article.category.id === category.id
      ).length;
    });
    
    // 按文章数量排序（降序）
    initialCategories.sort((a, b) => b.count - a.count);
    
    categories.value = initialCategories;
  } catch (error) {
    console.error('获取分类数据失败:', error);
  }
};

// 组件挂载时获取分类数据
onMounted(() => {
  fetchCategories();
});
</script>

<style scoped>
.categories-page {
  padding: 40px 0;
}

.page-header {
  text-align: center;
  margin-bottom: 50px;
}

.page-title {
  font-size: 36px;
  font-weight: bold;
  color: #333;
  margin-bottom: 15px;
}

.page-description {
  font-size: 18px;
  color: #666;
  max-width: 700px;
  margin: 0 auto;
}

.categories-container {
  max-width: 1200px;
  margin: 0 auto;
}

.categories-list {
  display: grid;
  grid-template-columns: 1fr;
  gap: 20px;
}

@media (min-width: 768px) {
  .categories-list {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (min-width: 1024px) {
  .categories-list {
    grid-template-columns: repeat(3, 1fr);
  }
}

@media (min-width: 1200px) {
  .categories-list {
    grid-template-columns: repeat(4, 1fr);
  }
}

.category-card {
  background-color: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  overflow: hidden;
  transition: all 0.3s;
}

.category-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 5px 20px rgba(0, 0, 0, 0.15);
}

.category-link {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 30px 20px;
  text-decoration: none;
  color: inherit;
  height: 100%;
}

.category-icon {
  margin-bottom: 20px;
  color: #4a6fa5;
  background-color: #f0f7ff;
  width: 80px;
  height: 80px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.category-info {
  text-align: center;
}

.category-name {
  font-size: 20px;
  font-weight: bold;
  color: #333;
  margin-bottom: 8px;
}

.category-count {
  font-size: 14px;
  color: #666;
  margin-bottom: 12px;
}

.category-description {
  font-size: 14px;
  color: #999;
  line-height: 1.6;
}

/* 响应式设计 */
@media (max-width: 767px) {
  .page-title {
    font-size: 28px;
  }
  
  .page-description {
    font-size: 16px;
  }
  
  .category-icon {
    width: 60px;
    height: 60px;
  }
  
  .category-icon svg {
    width: 36px;
    height: 36px;
  }
  
  .category-name {
    font-size: 18px;
  }
}
</style>
